In [2]:
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt


#Load the dataset
dataset = load_dataset("lukebarousse/data_jobs")
df = dataset['train'].to_pandas()

#Data cleanup
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [3]:
df['job_skills'].sample(10)

478759    ['python', 'r', 'aws', 'azure', 'hadoop', 'spa...
381982                                         ['power bi']
188946    ['python', 'sql', 'pandas', 'numpy', 'nltk', '...
497640          ['sql', 'sas', 'sas', 'python', 'r', 'vue']
473991                                                 None
778069    ['sql', 'python', 'snowflake', 'databricks', '...
496380                                              ['sql']
79288     ['python', 'java', 'sql', 'databricks', 'aws',...
396553                 ['sql', 'power bi', 'word', 'excel']
314087    ['python', 'sql', 'java', 'scala', 'snowflake'...
Name: job_skills, dtype: object

In [4]:
df["job_skills"].dropna().apply(type).value_counts()

job_skills
<class 'str'>    668704
Name: count, dtype: int64

In [16]:
import ast

import ast

def clean_skills(x):
    if isinstance(x, list):
        return x
    elif pd.isna(x):
        return []
    elif isinstance(x, str):
        return ast.literal_eval(x)
    else:
        return []

df["job_skills_clean"] = df["job_skills"].apply(clean_skills)
df['job_skills_clean'].sample(10)

109247                         [sql, python, gcp, bigquery]
409349                                     [sql, python, r]
358319                              [python, qlik, tableau]
718046    [sql, shell, nosql, python, java, scala, sql s...
768053       [python, r, tensorflow, pytorch, scikit-learn]
51996                                   [sql, java, oracle]
615920                       [sql, tableau, alteryx, excel]
96413                 [azure, databricks, spark, terraform]
679818                                      [sql, power bi]
710595    [r, python, sql, c, scikit-learn, tensorflow, ...
Name: job_skills_clean, dtype: object

In [17]:
skills_df = df[["job_title_short","job_country", "job_work_from_home","job_posted_date","job_skills_clean"]].copy()

In [19]:
skills_df = skills_df.explode('job_skills_clean')
skills_df

,job_title_short,job_country,job_work_from_home,job_posted_date,job_skills_clean
0,Senior Data Engineer,United States,False,2023-06-16 13:44:15,NaN
1,Data Analyst,Mexico,False,2023-01-14 13:18:07,r
1,Data Analyst,Mexico,False,2023-01-14 13:18:07,python
1,Data Analyst,Mexico,False,2023-01-14 13:18:07,sql
1,Data Analyst,Mexico,False,2023-01-14 13:18:07,nosql
...,...,...,...,...,...
785739,Data Engineer,Sudan,False,2023-03-12 06:32:15,kafka
785739,Data Engineer,Sudan,False,2023-03-12 06:32:15,kubernetes
785739,Data Engineer,Sudan,False,2023-03-12 06:32:15,docker
785740,Software Engineer,India,False,2023-03-13 06:16:31,aws
785740,Software Engineer,India,False,2023-03-13 06:16:31,flow

In [22]:
skills_df = skills_df.rename(columns={'job_skills_clean':'skill'})

In [25]:
skills_df = skills_df.dropna(subset=["skill"])
skills_df['skill'] = skills_df['skill'].str.lower().str.strip()
skills_df

,job_title_short,job_country,job_work_from_home,job_posted_date,skill
1,Data Analyst,Mexico,False,2023-01-14 13:18:07,r
1,Data Analyst,Mexico,False,2023-01-14 13:18:07,python
1,Data Analyst,Mexico,False,2023-01-14 13:18:07,sql
1,Data Analyst,Mexico,False,2023-01-14 13:18:07,nosql
1,Data Analyst,Mexico,False,2023-01-14 13:18:07,power bi
...,...,...,...,...,...
785739,Data Engineer,Sudan,False,2023-03-12 06:32:15,kafka
785739,Data Engineer,Sudan,False,2023-03-12 06:32:15,kubernetes
785739,Data Engineer,Sudan,False,2023-03-12 06:32:15,docker
785740,Software Engineer,India,False,2023-03-13 06:16:31,aws
785740,Software Engineer,India,False,2023-03-13 06:16:31,flow

In [26]:
skills_df["skill"].value_counts().head(30)

skill
sql           384849
python        380909
aws           145381
azure         132527
r             130892
tableau       127213
excel         127018
spark         114609
power bi       98147
java           85612
sas            83404
hadoop         64842
scala          56886
snowflake      55015
databricks     53182
gcp            50727
git            50226
kafka          49926
airflow        45254
oracle         45221
nosql          45070
docker         41715
sql server     40197
go             38634
kubernetes     37349
mongodb        36364
redshift       33406
tensorflow     33190
pyspark        32201
pandas         32188
Name: count, dtype: int64