In [1]:
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt


#Load the dataset
dataset = load_dataset("lukebarousse/data_jobs")
df = dataset['train'].to_pandas()

#Data cleanup
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

In [2]:
df['job_skills'].sample(10)

361511    ['javascript', 'oracle', 'aws', 'redshift', 't...
400854                                                 None
743083    ['sql', 't-sql', 'nosql', 'python', 'azure', '...
607506    ['sql', 'sql server', 'azure', 'ssis', 'ssrs',...
697070    ['sql', 'powershell', 'azure', 'databricks', '...
607275    ['aws', 'gcp', 'azure', 'spark', 'git', 'docke...
290849                                 ['outlook', 'excel']
471370    ['sql', 'python', 'r', 'snowflake', 'aws', 'az...
133076                               ['sql', 'r', 'python']
611324                                    ['python', 'sql']
Name: job_skills, dtype: object

In [3]:
df["job_skills"].dropna().apply(type).value_counts()

job_skills
<class 'str'>    668704
Name: count, dtype: int64

In [4]:
import ast

import ast

def clean_skills(x):
    if isinstance(x, list):
        return x
    elif pd.isna(x):
        return []
    elif isinstance(x, str):
        return ast.literal_eval(x)
    else:
        return []

df["job_skills_clean"] = df["job_skills"].apply(clean_skills)
df['job_skills_clean'].sample(10)

484521                                  [word, excel, flow]
693073                                                [sql]
109330    [sql, python, c#, sql server, azure, power bi,...
397021                           [sql, python, r, power bi]
237449                                        [python, sql]
589203                         [python, sql, matlab, excel]
647972    [java, c#, python, perl, groovy, javascript, o...
186923                                                   []
585486                                                   []
450931    [python, bash, powershell, databricks, aws, te...
Name: job_skills_clean, dtype: object

In [5]:
skills_df = df[["job_title_short","job_country", "job_work_from_home","job_posted_date","job_skills_clean"]].copy()

In [6]:
skills_df = skills_df.explode('job_skills_clean')
skills_df

,job_title_short,job_country,job_work_from_home,job_posted_date,job_skills_clean
0,Senior Data Engineer,United States,False,2023-06-16 13:44:15,NaN
1,Data Analyst,Mexico,False,2023-01-14 13:18:07,r
1,Data Analyst,Mexico,False,2023-01-14 13:18:07,python
1,Data Analyst,Mexico,False,2023-01-14 13:18:07,sql
1,Data Analyst,Mexico,False,2023-01-14 13:18:07,nosql
...,...,...,...,...,...
785739,Data Engineer,Sudan,False,2023-03-12 06:32:15,kafka
785739,Data Engineer,Sudan,False,2023-03-12 06:32:15,kubernetes
785739,Data Engineer,Sudan,False,2023-03-12 06:32:15,docker
785740,Software Engineer,India,False,2023-03-13 06:16:31,aws
785740,Software Engineer,India,False,2023-03-13 06:16:31,flow

In [7]:
skills_df = skills_df.rename(columns={'job_skills_clean':'skill'})

In [8]:
skills_df = skills_df.dropna(subset=["skill"])
skills_df['skill'] = skills_df['skill'].str.lower().str.strip()
skills_df

,job_title_short,job_country,job_work_from_home,job_posted_date,skill
1,Data Analyst,Mexico,False,2023-01-14 13:18:07,r
1,Data Analyst,Mexico,False,2023-01-14 13:18:07,python
1,Data Analyst,Mexico,False,2023-01-14 13:18:07,sql
1,Data Analyst,Mexico,False,2023-01-14 13:18:07,nosql
1,Data Analyst,Mexico,False,2023-01-14 13:18:07,power bi
...,...,...,...,...,...
785739,Data Engineer,Sudan,False,2023-03-12 06:32:15,kafka
785739,Data Engineer,Sudan,False,2023-03-12 06:32:15,kubernetes
785739,Data Engineer,Sudan,False,2023-03-12 06:32:15,docker
785740,Software Engineer,India,False,2023-03-13 06:16:31,aws
785740,Software Engineer,India,False,2023-03-13 06:16:31,flow

In [9]:
skills_df["skill"].value_counts().head(30)

skill
sql           384849
python        380909
aws           145381
azure         132527
r             130892
tableau       127213
excel         127018
spark         114609
power bi       98147
java           85612
sas            83404
hadoop         64842
scala          56886
snowflake      55015
databricks     53182
gcp            50727
git            50226
kafka          49926
airflow        45254
oracle         45221
nosql          45070
docker         41715
sql server     40197
go             38634
kubernetes     37349
mongodb        36364
redshift       33406
tensorflow     33190
pyspark        32201
pandas         32188
Name: count, dtype: int64

In [12]:
# How to skills differ by role?

roll_skills_counts = (skills_df.groupby(["job_title_short", "skill"]).size().reset_index(name="count"))
roll_skills_counts

        job_title_short     skill  count
0      Business Analyst   airflow    318
1      Business Analyst  airtable     17
2      Business Analyst   alteryx   1078
3      Business Analyst   angular     87
4      Business Analyst   ansible    120
...                 ...       ...    ...
2251  Software Engineer     wrike      4
2252  Software Engineer       wsl     13
2253  Software Engineer   xamarin     35
2254  Software Engineer      yarn    145
2255  Software Engineer      zoom    229

[2256 rows x 3 columns]